name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Show Build SDK
      run: xcodebuild -showsdks
    
    - name: Run Build
      run: swift build
